image:
  - Visual Studio 2022

build: off

clone_folder: c:\gopath\src\github.com\$username\$project

environment:
  GOPATH: c:\gopath

before_test:
  - set GOROOT=c:\go

test_script:
  - cd go
  - go vet ./...
  - go test ./...
  - go test ./Stats -fuzz=Stats1 -fuzztime=1s
  - go test ./Stats -fuzz=Stats2 -fuzztime=1s
  - go test ./Stats -fuzz=StatsN -fuzztime=2s
  - go test ./BronKerbosch -fuzz=DegeneracyOrder -fuzztime=5s
  - cd ..
