image:
  - Visual Studio 2017
platform:
  - x64
environment:
  # Copied from https://github.com/rust-lang/libc/blob/master/appveyor.yml
  RUSTUP_USE_REQWEST: 1
  CARGO_HTTP_CHECK_REVOKE: false
  matrix:
    - python: "C:\\Python37-x64"
install: 
  - PATH C:\python37-x64;C:\python37-x64\Scripts;%PATH%
  - python -V
  - python -m pip install --upgrade pip
  - pip install mypy pytest
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - PATH %PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
test_script:
  - mypy --cache-dir=/dev/null --ignore-missing-import python3
  - pytest -p no:cacheprovider python3
  - cd rust && cargo test --all
  - set GOPATH=%CD%\go && go test bron_kerbosch
