image:
  - Visual Studio 2017
platform:
  - x64
environment:
  # Copied from https://github.com/rust-lang/libc/blob/master/appveyor.yml
  RUSTUP_USE_REQWEST: 1
  CARGO_HTTP_CHECK_REVOKE: false
  matrix:
    - python: "C:\\Python37-x64"
install: 
  - PATH C:\python37-x64;C:\python37-x64\Scripts;%PATH%
  - python -V
  - python -m pip install --upgrade pip
  - pip install mypy pytest
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - PATH %PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  - MSBuild.exe
  - "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\MSBuild\\15.0\\Bin\\MSBuild.exe" csharp\BronKerboschStudy.sln
test_script:
  - mypy --cache-dir=/dev/null --ignore-missing-import python3
  - pytest -p no:cacheprovider python3
  - set GOPATH=%CD%\go&& go test bron_kerbosch
  - pushd rust && cargo test --all & popd
  - vstest.console.exe csharp\BronKerboschUnitTest\bin\Debug\BronKerboschUnitTest.dll
