image:
  - Visual Studio 2017
platform:
  - Any CPU
configuration:
  - Debug
environment:
  # Copied from https://github.com/rust-lang/libc/blob/master/appveyor.yml
  RUSTUP_USE_REQWEST: 1
  CARGO_HTTP_CHECK_REVOKE: false
  matrix:
    - python: "C:\\Python37-x64"
install: 
  - nuget restore csharp\BronKerboschStudy.sln
  - PATH C:\python37-x64;C:\python37-x64\Scripts;%PATH%
  - python -V
  - python -m pip install --upgrade pip
  - pip install mypy pytest
  - set GOPATH=%CD%\go
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - PATH %PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
build_script:
  - msbuild csharp\BronKerboschStudy.sln
  - pushd rust && cargo build & popd
test_script:
  - vstest.console csharp\BronKerboschUnitTest\bin\%CONFIGURATION%\BronKerboschUnitTest.dll csharp\BronKerboschStudyUnitTest\bin\%CONFIGURATION%\BronKerboschStudyUnitTest.dll
  - mypy --cache-dir=/dev/null --ignore-missing-import python3
  - pytest -p no:cacheprovider python3
  - go vet bron_kerbosch main
  - go test bron_kerbosch
  - pushd rust && cargo test --all & popd
