image:
  - Visual Studio 2022
install: 
  - python -V
  - pip install mypy pytest hypothesis --disable-pip-version-check
build: off
test_script:
  - mypy --cache-dir=/dev/null python3
  - pytest -p no:cacheprovider python3
  - pushd go
  - go vet ./...
  - go test ./...
  - go test ./Stats -fuzz=Stats1 -fuzztime=1s
  - go test ./Stats -fuzz=Stats2 -fuzztime=1s
  - go test ./Stats -fuzz=StatsN -fuzztime=2s
  - go test ./BronKerbosch -fuzz=DegeneracyOrder -fuzztime=5s
  - popd
