image:
  - Visual Studio 2019
platform:
  - Any CPU
configuration:
  - Debug
environment:
  matrix:
    - python: "C:\\Python37-x64"
install: 
  - nuget restore csharp\BronKerboschStudy.sln
  - PATH C:\python38-x64;C:\python38-x64\Scripts;%PATH%
  - python -V
  - pip install hypothesis mypy pytest --disable-pip-version-check
build_script:
  - msbuild csharp\BronKerboschStudy.sln
test_script:
  - dotnet test csharp\BronKerboschStudy.sln
  - mypy --cache-dir=/dev/null --strict python3
  - pytest -p no:cacheprovider python3
  - cd go
  - go vet BronKerbosch/...
  - go test BronKerbosch/...
  - go test -race BronKerbosch/lib
  - cd ..
