image: ubuntu
stack: python 3.7
environment:
  # Copied from https://github.com/rust-lang/libc/blob/master/appveyor.yml
  RUSTUP_USE_REQWEST: 1
  CARGO_HTTP_CHECK_REVOKE: false
install: 
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2_BITS PATH %PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -V
  - cargo -V
build_script:
  - mypy --cache-dir=/dev/null --ignore-missing-import python3
test_script:
  - pytest -p no:cacheprovider python3
  - cd rust && cargo test
