image:
  - Visual Studio 2017
platform:
  - Any CPU
configuration:
  - Debug
environment:
  matrix:
    - python: "C:\\Python37-x64"
install: 
  - nuget restore csharp\BronKerboschStudy.sln
  - PATH C:\python38-x64;C:\python38-x64\Scripts;%PATH%
  - python -V
  - pip install hypothesis mypy pytest --disable-pip-version-check
  - set GOPATH=%CD%\go
build_script:
  - msbuild csharp\BronKerboschStudy.sln
test_script:
  - vstest.console csharp\BronKerboschUnitTest\bin\%CONFIGURATION%\BronKerboschUnitTest.dll csharp\BronKerboschStudyUnitTest\bin\%CONFIGURATION%\BronKerboschStudyUnitTest.dll
  - mypy --cache-dir=/dev/null --ignore-missing-import python3
  - pytest -p no:cacheprovider python3
  - go vet BronKerbosch main
  - go test -race BronKerbosch
