[package]
name = "compare_bron_kerbosch_on_random_graphs"
version = "0.1.0"
authors = ["Stein Somers <git@steinsomers.be>"]

[profile.release]
debug = true

[workspace]

[dependencies]
bron_kerbosch = { path = "bron_kerbosch" }
random_graph = { path = "random_graph" }
stats = { path = "stats" }
csv = "1"
rand = "0.6.0"
rand_chacha = "0.1.0"
structopt = "0.2"
