[package]
name = "test_bron_kerbosch"
version = "0.1.0"
authors = ["Stein Somers <git@steinsomers.be>"]

[workspace]

[dependencies]
bron_kerbosch = { path = "bron_kerbosch" }
rand = "0.6.0"
rand_chacha = "0.1.0"
structopt = "0.2"
