[package]
name = "compare_bron_kerbosch_on_random_graphs"
version = "0.1.0"
authors = ["Stein Somers <git@steinsomers.be>"]

[profile.release]
debug = true

[workspace]

[dependencies]
bron_kerbosch = { path="bron_kerbosch" }
stats = { path="stats" }
csv = "1"
fnv = "1"
hashbrown = "0.6"
rand = "0.6"
itertools = "0.8"
rand_chacha = "0.1"
structopt = "0.2"
strum = "0.15"
strum_macros = "0.15"
