[package]
name = "compare_bron_kerbosch_on_random_graphs"
version = "1.0.0"
authors = ["Stein Somers <git@steinsomers.be>"]
edition = "2021"

[profile.release]
debug = true

[workspace]

[dependencies]
bron_kerbosch = { path="bron_kerbosch" }
stats = { path="stats" }
anyhow = "1.0.12"
clap = {version = "4.0.0", features = ["cargo"]}
csv = "1.0.0"
fnv = "1.0.5"
hashbrown = "0.13.0"
itertools = "0.10.0"
strum = "0.24.0"
strum_macros = "0.24.0"
