[package]
name = "compare_bron_kerbosch_on_random_graphs"
version = "0.1.0"
authors = ["Stein Somers <git@steinsomers.be>"]
edition = "2018"

[profile.release]
debug = true

[workspace]

[dependencies]
bron_kerbosch = { path="bron_kerbosch" }
stats = { path="stats" }
csv = "1"
fnv = "1"
hashbrown = "0.7"
rand = "0.7"
itertools = "0.8"
rand_chacha = "0.2"
structopt = "0.3"
strum = "0.17"
strum_macros = "0.17"
